resources:
- configmap-app.yaml
- configmap-db.yaml
- persistentvolumeclaim-app.yaml
- persistentvolumeclaim-db.yaml
- service-api.yaml
- service-db.yaml
- service-web.yaml
- secretproviderclass.yaml
- serviceaccount.yaml
- deployment-db.yaml
- deployment-api.yaml
- deployment-web.yaml

# Change the image name and version
images:
- name: notavalidregistry.azurecr.io/api:v0.1.0
  newName: <YOUR_ACR_SERVER>/api
  newTag: <YOUR_IMAGE_TAG>
- name: notavalidregistry.azurecr.io/web:v0.1.0
  newName: <YOUR_ACR_SERVER>/web
  newTag: <YOUR_IMAGE_TAG>
  
patches:
- patch: |-
    - op: replace
      path: "/metadata/name"
      value: <YOUR_SERVICE_ACCOUNT_NAME>
  target:
    kind: ServiceAccount
- patch: |-
    - op: replace
      path: "/metadata/annotations/azure.workload.identity~1client-id"
      value: <YOUR_MANAGED_IDENTITY_CLIENT_ID>
  target:
    kind: ServiceAccount
- patch: |-
    - op: replace
      path: "/spec/parameters/clientID"
      value: <YOUR_MANAGED_IDENTITY_CLIENT_ID>
  target:
    kind: SecretProviderClass
- patch: |-
    - op: replace
      path: "/spec/parameters/keyvaultName"
      value: <YOUR_KEY_VAULT_NAME>
  target:
    kind: SecretProviderClass
- patch: |-
    - op: replace
      path: "/spec/parameters/tenantId"
      value: <YOUR_TENANT_ID>
  target:
    kind: SecretProviderClass
- patch: |-
    - op: replace
      path: "/spec/template/spec/serviceAccountName"
      value: <YOUR_SERVICE_ACCOUNT_NAME>
  target:
    kind: Deployment