apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapi-v2
  labels:
    app: chatapi
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapi
      version: v2
  template:
    metadata:
      labels:
        app: chatapi
        version: v2
    spec:
      containers:
        - name: chatapi
          image: acrbuild20237248.azurecr.io/eshop/chatapi:v1.1.0
          ports:
            - containerPort: 80
          env:
            - name: AzureOpenAISettings__Endpoint
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_ENDPOINT
            - name: AzureOpenAISettings__Key
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_KEY
            - name: AzureOpenAISettings__ChatCompletionModel__Alias
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_CHATCOMPLETION_MODEL_ALIAS
            - name: AzureOpenAISettings__ChatCompletionModel__DeploymentName
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_CHATCOMPLETION_MODEL_DEPLOYMENT
            - name: AzureOpenAISettings__EmbeddingGenerationModel__Alias
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_EMBEDDING_MODEL_ALIAS
            - name: AzureOpenAISettings__EmbeddingGenerationModel__DeploymentName
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_EMBEDDING_MODEL_DEPLOYMENT
            - name: AzureOpenAISettings__TextCompletionModel__Alias
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_TEXTCOMPLETION_MODEL_ALIAS
            - name: AzureOpenAISettings__TextCompletionModel__DeploymentName
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: AOAI_TEXTCOMPLETION_MODEL_DEPLOYMENT
          resources:
            requests:
              cpu: 5m
              memory: 128Mi
            limits:
              cpu: 10m
              memory: 256Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chatapi
spec:
  host: chatapi.eshop.svc.cluster.local
  subsets:
    - name: version-v1
      labels:
        version: v1
    - name: version-v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chatapi
spec:
  hosts:
    - "*"
  gateways:
    - chatapi
  http:
    - match:
        - uri:
            prefix: /shopassist
          headers:
            x-istio-msbuild:
              exact: "brk225h"
      route:
        - destination:
            host: chatapi
            subset: version-v2
    - match:
        - uri:
            prefix: /shopassist
      route:
        - destination:
            host: chatapi
            subset: version-v1
