resources:
  - publicapi-v1.yaml
  - web-v1.yaml
  - chatapi-v1.yaml

# Change the image name and version
images:
  - name: chatapi
    newName: eshop/chatapi
    newTag: v1
  - name: publicapi
    newName: eshop/publicapi
    newTag: v1
  - name: web
    newName: eshop/web
    newTag: v1

configMapGenerator:
  - envs:
      - .env
    name: configs

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
