apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicapi
  labels:
    app: publicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publicapi
  template:
    metadata:
      labels:
        app: publicapi
    spec:
      containers:
        - name: publicapi
          image: eshop/publicapi:v1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CatalogConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_CATALOG
            - name: ConnectionStrings__IdentityConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_IDENTITY
            - name: baseUrls__webBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: WEB_URL
            - name: baseUrls__apiBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: API_URL
          resources:
            requests:
              cpu: 5m
              memory: 128Mi
            limits:
              cpu: 10m
              memory: 512Mi
          volumeMounts:
            - name: aspnet
              mountPath: ~/.aspnet/https:/root/.aspnet/https:ro
      volumes:
        - name: aspnet
          persistentVolumeClaim:
            claimName: aspnet-data
---
apiVersion: v1
kind: Service
metadata:
  name: publicapi
spec:
  selector:
    app: publicapi
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: publicapi
spec:
  hosts:
    - "*"
  gateways:
    - eshop-ingressgateway-external
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: publicapi
            port:
              number: 80
