apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
        - name: web
          image: eshop/web:v1
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 60
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CatalogConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_CATALOG
            - name: ConnectionStrings__IdentityConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_IDENTITY
            - name: ConnectionStrings__AppConfigConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: APP_CONFIG_CONNECTION
            - name: baseUrls__webBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: WEB_URL
            - name: baseUrls__apiBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: API_URL
            - name: baseUrls__chatBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: CHAT_URL
          resources:
            requests:
              cpu: 25m
              memory: 512Mi
            limits:
              cpu: 50m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web
spec:
  hosts:
    - "*"
  gateways:
    - web
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: publicapi
            port:
              number: 80
    - route:
        - destination:
            host: web
            port:
              number: 80
