apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: eshop/web:v2
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 600
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CatalogConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_CATALOG
            - name: ConnectionStrings__IdentityConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_IDENTITY
            - name: ConnectionStrings__AppConfigConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: APP_CONFIG_CONNECTION
            - name: baseUrls__webBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: WEB_URL
            - name: baseUrls__apiBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: API_URL
          resources:
            requests:
              cpu: 25m
              memory: 512Mi
            limits:
              cpu: 50m
              memory: 1024Mi
          volumeMounts:
            - name: aspnet
              mountPath: ~/.aspnet/https:/root/.aspnet/https:ro
      volumes:
        - name: aspnet
          persistentVolumeClaim:
            claimName: aspnet-data
