apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: eshop/web:v1
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 60
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 600
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CatalogConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_CATALOG
            - name: ConnectionStrings__IdentityConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: SQL_CONNECTION_IDENTITY
            - name: ConnectionStrings__AppConfigConnection
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: APP_CONFIG_CONNECTION
            - name: baseUrls__webBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: WEB_URL
            - name: baseUrls__apiBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: API_URL
            - name: baseUrls__chatBase
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: CHAT_URL
          resources:
            requests:
              cpu: 40m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi
          volumeMounts:
            - name: aspnet
              mountPath: ~/.aspnet
      volumes:
        - name: aspnet
          persistentVolumeClaim:
            claimName: aspnet-data
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web
spec:
  hosts:
    - "*"
  gateways:
    - eshop-ingressgateway-external
  http:
    - route:
        - destination:
            host: web
            port:
              number: 80
